name: cd

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  cd:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up node env
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Generate
      run: npm run generate
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
